# Generated by Django 3.2.24 on 2024-09-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_category', models.CharField(max_length=20)),
                ('survey_fees', models.PositiveIntegerField()),
                ('local_authority_fees', models.PositiveIntegerField()),
            ],
        ),
    ]
