# Generated by Django 3.2.24 on 2024-09-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_photo',
            field=models.ImageField(default='uploads/survey/photo.jpg', upload_to='uploads/survey'),
        ),
    ]
