# Generated by Django 3.2.24 on 2024-09-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_survey_survey_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='client_category',
            field=models.CharField(choices=[('Industrial', 'Industrial'), ('Commercial', 'Commercial'), ('Domestic', 'Domestic')], max_length=20),
        ),
    ]
