# Generated by Django 3.2.24 on 2024-09-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='country',
            new_name='county',
        ),
    ]
