# Generated by Django 3.2.24 on 2024-09-10 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20240909_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='about',
        ),
    ]
