# Generated by Django 3.2.24 on 2024-09-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_remove_userprofile_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='survey_and_local_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industrial_survey_fee', models.PositiveIntegerField()),
                ('industrial_local_authority_fee', models.PositiveIntegerField()),
                ('commercial_survey_fee', models.PositiveIntegerField()),
                ('commercial_local_authority_fee', models.PositiveIntegerField()),
                ('domestic_survey_fee', models.PositiveIntegerField()),
                ('domestic_local_authority_fee', models.PositiveIntegerField()),
            ],
        ),
    ]
