# Generated by Django 3.2.24 on 2024-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_survey_and_local_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Survey_Category', models.CharField(max_length=50)),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Email_Address', models.EmailField(max_length=254)),
                ('Phone_Number', models.PositiveIntegerField()),
                ('Survey_Fee', models.PositiveIntegerField()),
                ('Local_Authority_Fee', models.PositiveIntegerField()),
                ('Total_Amount', models.PositiveIntegerField()),
            ],
        ),
    ]
