# Generated by Django 3.2.24 on 2024-09-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_survey_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(default='uploads/userprofile/user.png', upload_to='uploads/userprofile'),
        ),
    ]
