# Generated by Django 3.2.24 on 2024-09-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_alter_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/userprofile/profile.jpg', null=True, upload_to='uploads/userprofile'),
        ),
    ]
