# Generated by Django 3.2.24 on 2024-09-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_alter_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='uploads/profile/profile.jpg', upload_to='uploads/profiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
    ]
