# Generated by Django 3.2.24 on 2024-09-20 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_auto_20240918_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_photo',
            old_name='photo',
            new_name='profile_photos',
        ),
    ]
