# Generated by Django 3.2.24 on 2024-09-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_rename_photo_profile_photo_profile_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_application',
            name='Amount_paid',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='survey_application',
            name='Mpesa_phone',
            field=models.PositiveIntegerField(default='0000000000'),
        ),
    ]
