# Generated by Django 3.2.24 on 2024-09-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_auto_20240923_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_application',
            name='Amount_paid',
            field=models.PositiveIntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='survey_application',
            name='Mpesa_phone',
            field=models.PositiveIntegerField(default='0000000000', null=True),
        ),
    ]
