# Generated by Django 3.2.24 on 2024-09-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_auto_20240923_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, default='uploads/profile/profile.jpg', null=True, upload_to='uploads/profile'),
        ),
    ]
