# Generated by Django 3.2.24 on 2024-09-23 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_auto_20240923_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo',
            new_name='profile_photos',
        ),
    ]
