# Generated by Django 3.2.24 on 2024-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_alter_survey_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_photos',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='p_photo',
            field=models.ImageField(default='uploads/profile/profile.jpg', upload_to='uploads/profile'),
        ),
    ]
