# Generated by Django 3.2.24 on 2024-10-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_survey_application_depth'),
    ]

    operations = [
        migrations.CreateModel(
            name='down_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Symmetric drilling', 'Symmetric drilling'), ('Core drilling', 'Core drilling'), ('Geo-Technical drilling', 'Geo-Technical drilling')], max_length=50)),
                ('downpayment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
