# Generated by Django 3.2.24 on 2024-10-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0023_down_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='down_payment',
            new_name='Payment',
        ),
    ]
