# Generated by Django 3.2.24 on 2024-10-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0024_rename_down_payment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(choices=[('Symmetric Drilling', 'Symmetric Drilling'), ('Core Drilling', 'Core Drilling'), ('Geo-Technical Drilling', 'Geo-Technical Drilling')], max_length=50),
        ),
    ]
