# Generated by Django 3.2.24 on 2024-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0027_alter_payment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_application',
            name='height',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='survey_application',
            name='depth',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
