# Generated by Django 3.2.24 on 2024-10-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0028_auto_20241022_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump', models.CharField(choices=[('Submersible Electric Pump', 'Submersible Electric Pump'), ('Solar Pump', 'Solar Pump'), ('Hand Pump', 'Hand Pump')], max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
