# Generated by Django 3.2.24 on 2024-10-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0029_pump'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.CharField(choices=[('Household Tank Plastic', 'Household Tank Plastic'), ('Household Steel Tank', 'Household Steel Tank'), ('Large Steel Tank', 'Large Steel Tank')], max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
