# Generated by Django 3.2.24 on 2024-10-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0031_drilling_and_pump_installation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=50)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mpesa_receipt_number', models.CharField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('result_code', models.IntegerField()),
                ('result_desc', models.CharField(max_length=255)),
            ],
        ),
    ]
