# Generated by Django 3.2.24 on 2024-11-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0034_auto_20241104_1117'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaPayment',
        ),
        migrations.AddField(
            model_name='drilling_and_pump_installation',
            name='status1',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed')], default='In progress', max_length=100),
        ),
        migrations.AlterField(
            model_name='survey_application',
            name='depth',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='survey_application',
            name='height',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
