# Generated by Django 3.2.24 on 2024-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0035_auto_20241105_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drilling_and_pump_installation',
            name='status1',
            field=models.CharField(choices=[('In progress', 'In progress'), ('On site', 'On site'), ('Completed', 'Completed')], default='In progress', max_length=100),
        ),
    ]
