# Generated by Django 3.2.24 on 2024-11-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0037_mpesatransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tank_photo',
            field=models.ImageField(default='uploads/tanks/tank.jpg', upload_to='uploads/tanks'),
        ),
    ]
