# Generated by Django 3.2.24 on 2024-11-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0038_tank_tank_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='pump_photo',
            field=models.ImageField(default='uploads/tanks/tank.jpg', upload_to='uploads/pumps'),
        ),
    ]
