# Generated by Django 3.2.24 on 2024-09-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('blog_name', models.CharField(max_length=50)),
                ('blog_description', models.CharField(max_length=200)),
                ('image', models.ImageField(default='uploads/blogs/blog.jpg', upload_to='uploads/blogs')),
            ],
        ),
    ]
