# Generated by Django 3.2.24 on 2024-09-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_contact1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact1',
            new_name='messagess',
        ),
    ]
