# Generated by Django 3.2.24 on 2024-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('welcome', '0004_rename_contact1_messagess'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('pick_date', models.DateField()),
                ('pick_time', models.TimeField()),
            ],
        ),
    ]
