# Generated by Django 3.2.24 on 2024-09-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0005_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pick_time',
            field=models.CharField(max_length=20),
        ),
    ]
