# Generated by Django 3.2.24 on 2024-09-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0006_alter_booking_pick_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='query_type',
            field=models.CharField(choices=[('Select Your Query Type', 'Select Your Query Type'), ('Surveys and Local Fees', 'Surveys and Local Fees'), ('Drilling Services', 'Drilling Services'), ('Pump Installation', 'Pump Installation')], max_length=50),
        ),
    ]
