# Generated by Django 3.2.24 on 2024-11-23 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0009_alter_booking_pick_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagess',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
