# Generated by Django 3.2.24 on 2024-11-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0010_messagess_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='XXXXXXXX', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='XXXXXXXX', max_length=13),
        ),
    ]
